name: Build and Run Kotlin App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        echo "apiKey=${{ secrets.APIKEY }}" > config.example

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build asemble

    - name: Run JAR
      run: java -jar build/libs/DR1ommer-0.1.jar config.example

    - name: Upload feed.xml as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: feed-artifact
        path: ~/genstart/feed.xml
